### ISSUE TITLE
Configuration injection is not optional

### ISSUE THREAD

**Issue by GuiSim** [supercargo/guice-persist-jooq#4]
```
  @Inject
  private Configuration configuration = null;
```

The documentation mentions that providing a Configuration instance is optional but that is not the case. In order to declare an Inject as optional, you need to use `@Inject(optional=true)`. It should also probably be `@Nullable`.

See https://github.com/google/guice/wiki/Injections#optional-injections

If you agree, I'll do a pull request with a fix.

EDIT: The same seems true for `Settings`

**Comment by supercargo** [comment]
Yes, thank you for the report.  Happy to take a look at a PR.
